### ISSUE TITLE
Consdier downgrading to 2.0.5

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/flatbuffers-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It seems that flatbuffers removed important generated code in 2.0.6

https://github.com/google/flatbuffers/issues/7272

### Installed packages

```shell
tensorflow builds failed with 2.0.6
https://github.com/conda-forge/tensorflow-feedstock/pull/218
```

### Environment info

```shell
.
```

**Comment by jakirkham** [comment]
A new branch with an older version could be created if you are just looking for that version

**Comment by hmaarrfk** [comment]
Apparently tensorflow needs to generate its sources.
https://github.com/google/flatbuffers/issues/7217

Is this a header only library? Is it safe to build with 2.0.5 and run with 2.0.6?

**Comment by hmaarrfk** [comment]
Well the release notes go from:

* 2.0.0
* 2.0.5
* 2.0.6

But 2.0.5 only states that it is the last release that supports some older versions of Visual Studio. I'm not so inclined to create a tag. I'm going to attempt to continue building with 2.0.0 until something breaks.

**Comment by jakirkham** [comment]
> Is this a header only library?

No this also has a dynamic library.

> Is it safe to build with 2.0.5 and run with 2.0.6?

Not sure. Currently we don't have `run_exports` here ( though we should add that https://github.com/conda-forge/flatbuffers-feedstock/issues/26 ).

Looking at [the ABI tracker]( https://abi-laboratory.pro/index.php?view=timeline&l=flatbuffers ) suggests minor releases (not patch releases) breaking things, but there are not a lot of patch releases to compare and the listing is a bit out-of-date. Raised here ( https://github.com/lvc/abi-tracker/issues/17 )

> I'm not so inclined to create a tag. I'm going to attempt to continue building with 2.0.0 until something breaks.

Sounds reasonable. Should we close then? Or do you want to keep open in case something does break and we need to revisit?

**Comment by hmaarrfk** [comment]
I would like to keep this open for a bit longer. We can close in a few months.
