### ISSUE TITLE
Add `run_exports`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/flatbuffers-feedstock#26]
Currently `run_exports` is not being added here. Looking at [the ABI compatibility]( https://abi-laboratory.pro/index.php?view=timeline&l=flatbuffers ), pinning to minor (and letting patch float) seems sufficient.

Though recent releases haven't been covered yet. Filed issue ( https://github.com/lvc/abi-tracker/issues/17 ) on that.

**Comment by hmaarrfk** [comment]
We just hit this in https://github.com/conda-forge/tensorflow-feedstock/issues/290 when version 22.X.X introduced an SO name change from 2.X.X
