### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by wesm** [conda-forge/flatbuffers-feedstock#3]
flatc should build fine on Windows with cmake, can anyone help?

**Comment by maxhora** [comment]
@wesm https://github.com/conda-forge/flatbuffers-feedstock/pull/5

**Comment by wesm** [comment]
Only vc14 is enabled right now https://anaconda.org/conda-forge/flatbuffers/files -- if we want vc10 builds, does the feedstock need to be rerendered?

**Comment by jakirkham** [comment]
So conda-forge dropped Python 3.4, which used vc10. ATM there is no easy way to use vc10 without Python 3.4. Is there a particular reason you want to use that vc?

**Comment by wesm** [comment]
I was just curious. It's in the meta.yaml, so we should drop that. I'm cool with only Python 3.5 and 3.6

**Comment by jakirkham** [comment]
Ok, if you change your mind, let us know and we can chat more.
