### ISSUE TITLE
What happened to version 24.3.6

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/flatbuffers-feedstock#50]
### Comment:

Did it get deleted
https://github.com/conda-forge/conda-forge-pinning-feedstock/commit/3bb04c5ca2d37a7628baa37512c2e627ccd096ba

https://anaconda.org/conda-forge/flatbuffers/files

@ilya-lavrenov noticed this https://github.com/conda-forge/openvino-feedstock/pull/93#discussion_r1594756102

**Comment by xhochy** [comment]
It looks like CI did not run on main.

**Comment by hmaarrfk** [comment]
how would the migration have happened if that were the case

**Comment by xhochy** [comment]
Keeping this screenshot as evidence: ![Image](https://github.com/user-attachments/assets/d824a9a2-6e70-42fe-8185-7fb3264974da)

I still don't know what happened 🤷 I'm closing it. If you really need the version, I'm happy to create a branch an retrigger CI.

**Comment by hmaarrfk** [comment]
no i guess we got through it.
